action_guide: false
batch_size: 20
device: cuda:0
env_port: 19999
eval_episode: 20
eval_gui: true
exp_idx: '1'
exp_name: s1
lr_rate: 0.0005
mse_loss: true
n_episode: 20
pretrain_demo: false
pretrain_save_step: 5
pretrain_step: 20
restore: false
reward_guide: false
save_every: 5
seed: 1000
tps: 1800
train_gui: false
update_step: 1
w_decay: 1.0e-05
